export const GET_NOTES = 'GET_NOTES';
export const GET_NOTES_FAIL = 'GET_NOTES_FAIL';

export const GET_NOTES_BY_CHAPTER = 'GET_NOTES_BY_CHAPTER';
export const GET_NOTES_BY_CHAPTER_FAIL = 'GET_NOTES_BY_CHAPTER_FAIL';

export const NOTES_LOADING = 'NOTES_LOADING';
export const NOTES_BY_CHAPTER_LOADING = 'NOTES_BY_CHAPTER_LOADING';

export const CREATE_NOTE = 'CREATE_NOTE';
export const CREATE_NOTE_FAIL = 'CREATE_NOTE_FAIL';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';

export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_FAIL = 'DELETE_NOTE_FAIL';

export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL';
