export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const SET_QUESTIONS = 'SET_QUESTIONS';

export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTION = 'GET_QUESTION';

export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTION_FAIL = 'ADD_QUESTION_FAIL';

export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const UPDATE_QUESTION_FAIL = 'UPDATE_QUESTION_FAIL';

export const DELETE_QUESTION = 'DELETE_QUESTION';
export const DELETE_QUESTION_FAIL = 'DELETE_QUESTION_FAIL';

